export const SET_CITY = "SET_CITY!";
export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const DELETE_CITY ="DELETE_CITY"

export const SET_FORECAST_DATA = "SET_FORECAST_DATA";
export const GET_FORECAST_DATA = "SET_FORECAST_DATA";
export const GET_FORECAST_DATA_START="SET_FORECAST_DATA_START";
export const GET_FORECAST_DATA_FAIL="SET_FORECAST_DATA_FAIL";
export const GET_FORECAST_DATA_SUCCESS="SET_FORECAST_DATA_SUCCES";



// for city search
export const SHOW_SEARCH_MODAL ="SHOW_SEARCH_MODAL";
export const HIDE_SEARCH_MODAL ="HIDE_SEARCH_MODAL"

export const SEARCH_CITY_START = "SEARCH_CITY_START";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_FAIL = "SEARCH_CITY_FAIL";
